---
- hosts: webservers
  gather_facts: yes
  tasks:
   - name: cache is updating
     become: yes
     apt:
      update_cache: yes
      cache_valid_time: 3600
   - name: To know if nginx is installed
     become: yes
     apt:
      name: nginx
      state: latest
   - name: php-fpm installing
     become: yes
     apt:
      name: php7.4-fpm 
      state: present
   - name: Starting nginx
     become: yes
     service:
         name: nginx
         state: started
   - name: Copying the php file
     become: yes
     copy:
       src: index.php
       dest: /var/www/html/
   - name: added the template file
     become: yes
     template:
       src: nginx.conf.j2
       dest: /etc/nginx/sites-available/default
   - name: confuration file enable
     become: yes
     file:
       src: /etc/nginx/sites-available/default
       dest: /etc/nginx/sites-enabled/default
       state: link
   - name: The Web Servers are restarting
     become: yes
     service:
       name: nginx
       state: restarted
- hosts: haproxy
  gather_facts: yes
  become: yes
  tasks:
   - name: Haproxy upadate
     apt:
      update_cache: yes
   - name: Installation haproxy
     become: yes
     apt:
      name: haproxy
      state: present
   - name: haproxy update configuration file
     template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
   - name: HAProxy reinitiation
     service:
       name: haproxy
       state: restarted
